"""
AION AST Cache
Caches parsed ASTs for faster repeated execution.
Auto-generated by self-development system.
"""

import hashlib
from typing import Optional, Dict
from pathlib import Path
import time

class ASTCache:
    """
    LRU cache for parsed AION ASTs.
    Dramatically speeds up repeated parsing of the same code.
    """
    
    def __init__(self, max_size: int = 100):
        self.max_size = max_size
        self.cache: Dict[str, tuple] = {}  # hash -> (ast, timestamp, hits)
        self.stats = {
            'hits': 0,
            'misses': 0,
            'evictions': 0
        }
    
    def _hash(self, source: str) -> str:
        """Generate cache key from source."""
        return hashlib.md5(source.encode()).hexdigest()
    
    def get(self, source: str):
        """Get cached AST if available."""
        key = self._hash(source)
        
        if key in self.cache:
            ast, timestamp, hits = self.cache[key]
            self.cache[key] = (ast, time.time(), hits + 1)
            self.stats['hits'] += 1
            return ast
        
        self.stats['misses'] += 1
        return None
    
    def put(self, source: str, ast):
        """Cache an AST."""
        key = self._hash(source)
        
        # Evict if full (remove least recently used)
        if len(self.cache) >= self.max_size:
            oldest_key = min(self.cache, key=lambda k: self.cache[k][1])
            del self.cache[oldest_key]
            self.stats['evictions'] += 1
        
        self.cache[key] = (ast, time.time(), 1)
    
    def clear(self):
        """Clear the cache."""
        self.cache.clear()
    
    @property
    def hit_rate(self) -> float:
        """Calculate cache hit rate."""
        total = self.stats['hits'] + self.stats['misses']
        return self.stats['hits'] / total if total > 0 else 0.0


# Global cache instance
_global_cache = ASTCache()

def cached_parse(source: str):
    """
    Parse with caching enabled.
    Drop-in replacement for parse().
    """
    from .parser import parse
    
    # Check cache
    cached = _global_cache.get(source)
    if cached is not None:
        return cached
    
    # Parse and cache
    ast = parse(source)
    _global_cache.put(source, ast)
    return ast

def get_cache() -> ASTCache:
    """Get the global AST cache."""
    return _global_cache
